apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-rolling
  namespace: aceest-fitness
  labels:
    app: aceest-fitness
    strategy: rolling-update
spec:
  type: LoadBalancer
  selector:
    app: aceest-fitness
    deployment: rolling
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30130
  sessionAffinity: None
