apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-shadow-prod
  namespace: aceest-fitness
  labels:
    app: aceest-fitness
spec:
  type: LoadBalancer
  selector:
    app: aceest-fitness
    version: production  # Only production receives user traffic
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30110
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-shadow-internal
  namespace: aceest-fitness
  labels:
    app: aceest-fitness
spec:
  type: ClusterIP
  selector:
    app: aceest-fitness
    version: shadow  # Shadow version for internal testing
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  sessionAffinity: None
